server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://rcdatabase.cuvca5zyxjf4.ap-northeast-2.rds.amazonaws.com:3306/baeminDB2?autoReconnect=true # 변경해주세요
    username: ankisile # 변경해주세요
    password: 6246alsdud! # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전